### ISSUE TITLE
Not printing to discord.

### ISSUE THREAD

**Issue by Proximity77** [ph03n1x9000/cod4xscreenshot-b3-plugin#1]
```
240522 17:19:01 ERROR    "Cod4XscreenshotPlugin: 'NoneType' object has no attribute 'value'"
240522 17:19:01 ERROR    'Cod4XscreenshotPlugin: coercing to Unicode: need string or buffer, NoneType found'
```

The screenshot takes, places onto the server but does not bounce back to imgbb or discord. Yes, the webhook is made and so is the API. Any suggestions?

**Comment by ph03n1x9000** [comment]
Sorry, I this was a very old version...didn't think anyone would use it. I have made several updates to this since... I will update for you soon.

**Comment by ph03n1x9000** [comment]
Plugin has been updated... let me know if it works for you @Proximity77

**Comment by Proximity77** [comment]
Updated seemed to get rid of one error. Still not printing the screenshot to imgbb. here is a new error. I also use the cod4x parser if that helps. Now its not even saving to the server. Seems to hang on taking the screenshot of "x"...

```
240523 21:07:35 ERROR    'STDERR \'Exception in thread Thread-49:\\nTraceback (most recent call last):\\n  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner\\n    self.run()\\n  File "/usr/local/lib/python2.7/threading.py", line 754, in run\\n    self.__target(*self.__args, **self.__kwargs)\\n  File "/home/container/b3/extplugins/cod4xscreenshot/__init__.py", line 133, in processloop\\n    screenshot_name_full = self.screenshotpath + screenshot_name + \\\'0000.jpg\\\'\\nTypeError: unsupported operand type(s) for +: \\\'NoneType\\\' and \\\'str\\\'\\n\''
240523 21:07:35 ERROR    "STDERR '\\n'"
```

**Comment by Proximity77** [comment]
Also still this error whoops.

`240523 21:06:42 ERROR    "Cod4XscreenshotPlugin: 'NoneType' object has no attribute 'value'"`

**Comment by ph03n1x9000** [comment]
Those 2 errors are related...it seems to be unique to your setup.. What that error is saying is that the plugin cannot get the sv_savepath from the server..normally that would disable the plugin all together, but your server seems to return a Nonetype instead which counts as a response. I will patch so that such issues are addressed. In this patch, I will make it so that you can indicate the savepath in the config.

**Comment by Proximity77** [comment]
That would be great thanks.

**Comment by ph03n1x9000** [comment]
It has been patched. Go ahead and update. Don't forget the config has a new setting as well.

**Comment by Proximity77** [comment]
Okay, patch fixed the errors. It now properly takes a screenshot and places it in the directory. But it does not upload to imgbb and place into my discord. Webhook is created, etc. If you would like a video feel free to add me on discord. Proximity77

**Comment by Proximity77** [comment]
Also, the screenshot file name no longer includes the player name.
